### PR TITLE
added full stop plugin

### PR DESCRIPTION
**Pull request by SophiaAtkinson**

### CODE REVIEW

**Review by dgw — APPROVED** [review]

**Comment by ozh** [comment]
Hi, thanks ! Could you please reorder it so it's alphabetical instead ? Would have done it but it seems you unchecked the option ;)

**Comment by ozh** [comment]
Never mind, just saw it was merged 😁 I'll do it

**Comment by SophiaAtkinson** [comment]
> Hi, thanks ! Could you please reorder it so it's alphabetical instead ? Would have done it but it seems you unchecked the option ;)

Sorry about that. But thanks for fixing it!

**Comment by dgw** [comment]
@ozh We don't have an automation workflow for sorting? 🤔 😁

**Pull request merged**
