### PR TITLE
Add en_AU

### PR DESCRIPTION
**Pull request by bakkbone**
I translated for en_AU

### CODE REVIEW

**Comment by ozh** [comment]
I didn't notice any change in the translation file ? so what is the point ? :)

**Comment by ozh** [comment]
I still dont get the point of this, nor what "our server flags EN_US".

Adding `define('YOURLS_LANG', 'en_AU');` to load an unmodified translation file is the same as doing nothing, or to do the define without adding any translation file... (except you're actually slowing things down a bit by loading an external file that contains the same strings as in core)

**Comment by bakkbone** [comment]
There are differences in spelling between US and AU English - as such our server is set to flag and repetitively notify admins for any installations not in AU English. Thus, we maintain en_AU translations for as many programs our clients use as we are able. Apologies for attempting to contribute this to the broader community ¯\_(ツ)_/¯

**Comment by bakkbone** [comment]
And as such, there are changes:

image
image

**Comment by dgw** [comment]
> as such our server is set to flag and repetitively notify admins for any installations not in AU English

This sounds like a waste of server resources. It's up to your _clients_ whether they want to present content in AU English or some other dialect, is it not?

**Comment by ozh** [comment]
If there are changes (even minor), then this is different of course. You should have stated that in the first place :)

**Comment by bakkbone** [comment]
> You should have stated that in the first place :)

Apologies - had assumed that much went without saying

**Pull request merged**
