### PR TITLE
Update Plugin URL: yourls-conditional-urlads

### PR DESCRIPTION
**Pull request by 8MiYile**
yourls-conditional-urlads

### CODE REVIEW

**Comment by ozh** [comment]
Hi, as I understand it, this is not a new URL for a plugin. Your plugin is an updated fork, hence a new plugin. Hence, the 2 should be mentioned.

**Comment by 8MiYile** [comment]
> Hi, as I understand it, this is not a new URL for a plugin. Your plugin is an updated fork, hence a new plugin. Hence, the 2 should be mentioned.

But the original author no longer cares about this plugin, I take over the updating and patching of this plugin and also allow adding multiple languages in terms of README

**Comment by ozh** [comment]
Yes. An updated fork.

**Comment by 8MiYile** [comment]
So it can be merged?

**Comment by LeoColomb** [comment]
As mentioned by @ozh, while adding yours is very welcome, it does not seem relevant to remove the other one, actively maintained by @HeroCC, the author.
Could you update your pull request to add it as a separate link?

**Comment by 8MiYile** [comment]
I've changed the docs and included that address from HeroCC in the Legacy tab

**Comment by 8MiYile** [comment]
And... you can see here that I've explained the change.
https://github.com/8Mi-Tech/yourls-conditional-urlads/blob/master/README/en_US.md#acknowledgements

**Comment by 8MiYile** [comment]
https://github.com/HeroCC/yourls-conditional-urlads/pull/6

**Comment by 8MiYile** [comment]
Okay, can you check out the changes I made?

**Comment by ozh** [comment]
This is another plugin. So it goes on another line.

**Comment by 8MiYile** [comment]
The plugins are the same, but I'm a radical and he's a conservative, so mine and his only distinguish between development and stable versions.

**Pull request closed without merging**
